/* SF Symbol name → lookalike icon component.
 *
 * Prompts and generated apps always carry the exact SF Symbols name (Apple's
 * license does not allow embedding SF Symbols in a web project), so the
 * canvas draws a close open-source lookalike from Lucide (ISC). Anything not
 * mapped falls back to the text glyph in lib/symbols.ts. */

import type { LucideIcon } from "lucide-react";
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  BadgeCheck,
  BatteryFull,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  Check,
  ChartBar,
  ChartPie,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeftRight,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleDollarSign,
  CircleMinus,
  CirclePlus,
  CircleX,
  Clock,
  Cloud,
  Crown,
  CreditCard,
  Download,
  Droplet,
  Ellipsis,
  File,
  Film,
  Flame,
  Footprints,
  Folder,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  House,
  Image,
  Inbox,
  KeyRound,
  LayoutGrid,
  Leaf,
  List,
  Lock,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  Music,
  Navigation,
  Pencil,
  PawPrint,
  Pause,
  Phone,
  PhoneCall,
  Plane,
  Play,
  Plus,
  QrCode,
  Repeat,
  RotateCcw,
  RotateCw,
  ScanFace,
  Search,
  Send,
  Settings,
  Share,
  Shield,
  Shuffle,
  ShoppingBag,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Star,
  Sun,
  SquarePen,
  Tag,
  Timer,
  Trash2,
  Tv,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  Wifi,
  X,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  // common
  house: House,
  gearshape: Settings,
  magnifyingglass: Search,
  plus: Plus,
  minus: Minus,
  xmark: X,
  checkmark: Check,
  person: User,
  "person.2": Users,
  heart: Heart,
  star: Star,
  bell: Bell,
  bookmark: Bookmark,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  trash: Trash2,
  pencil: Pencil,
  "square.and.pencil": SquarePen,
  folder: Folder,
  doc: File,
  book: BookOpen,
  tag: Tag,
  cart: ShoppingCart,
  bag: ShoppingBag,
  creditcard: CreditCard,
  gift: Gift,
  crown: Crown,
  key: KeyRound,
  lock: Lock,
  shield: Shield,
  "list.bullet": List,
  "square.grid.2x2": LayoutGrid,
  circle: Circle,
  seal: BadgeCheck,
  qrcode: QrCode,
  faceid: ScanFace,
  // media
  play: Play,
  pause: Pause,
  "forward.end": SkipForward,
  "backward.end": SkipBack,
  shuffle: Shuffle,
  repeat: Repeat,
  "speaker.wave.2": Volume2,
  mic: Mic,
  "music.note": Music,
  headphones: Headphones,
  photo: Image,
  camera: Camera,
  video: Video,
  film: Film,
  gamecontroller: Gamepad2,
  tv: Tv,
  // comms
  message: MessageSquare,
  envelope: Mail,
  phone: Phone,
  paperplane: Send,
  "phone.badge.waveform": PhoneCall,
  "bubble.left": MessageCircle,
  share: Share,
  "square.and.arrow.up": Upload,
  "square.and.arrow.down": Download,
  tray: Inbox,
  // arrows
  "chevron.left": ChevronLeft,
  "chevron.right": ChevronRight,
  "chevron.up": ChevronUp,
  "chevron.down": ChevronDown,
  "arrow.left": ArrowLeft,
  "arrow.right": ArrowRight,
  "arrow.up": ArrowUp,
  "arrow.down": ArrowDown,
  "arrow.clockwise": RotateCw,
  "arrow.counterclockwise": RotateCcw,
  "plus.circle": CirclePlus,
  "minus.circle": CircleMinus,
  "xmark.circle": CircleX,
  "checkmark.circle": CircleCheck,
  "chevron.left.chevron.right": ChevronsLeftRight,
  "chevron.up.chevron.down": ChevronsUpDown,
  ellipsis: Ellipsis,
  // objects & nature
  map: Map,
  location: Navigation,
  leaf: Leaf,
  flame: Flame,
  moon: Moon,
  "sun.max": Sun,
  cloud: Cloud,
  wifi: Wifi,
  "battery.100": BatteryFull,
  car: Car,
  airplane: Plane,
  bike: Bike,
  "figure.walk": Footprints,
  pawprint: PawPrint,
  "fork.knife": Utensils,
  drop: Droplet,
  waveform: AudioLines,
  "chart.bar": ChartBar,
  "chart.pie": ChartPie,
  graduationcap: GraduationCap,
  briefcase: Briefcase,
  building: Building2,
  wallet: Wallet,
  dollarsign: CircleDollarSign,
};

// lucide-react exports these directly; they were verified against the
// installed package version (all names above resolve).
export const ICON_COUNT = Object.keys(MAP).length;

export function iconFor(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined;
  return MAP[name];
}
